### PR TITLE
Replaces Hand Rolled argument parsing with structopt 0.3

### PR DESCRIPTION
**Pull request by oldwomanjosiah**
### Motivation:

Hand-rolled argument parsing can be brittle. For instance the commands
```bash
comfy --c --file comfy.comfy
# and
comfy --file comfy.comfy --c
```
would, to any reader, be synonymous, but to the parser (as is) only the second would be valid.  
Another issue is that it is exceedingly easy to change something about the parser and forget to update the help message, which can often lead to frustrations for the end-user as the application is lying to you about what you can and cannot do with it.

By using [structopt](https://crates.io/crates/structopt) to define the structure of the arguments to the program we get a few nice things for free:

- non-positional arguments become truly non-positional
- paths captured using [PathBuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html) are validated for you  
    (May not be valid files, but will be valid paths for any system it's used on)
- Implementation of the main function is much more readable
- Help information is automatically kept up to date with actual implementation.

### Specific Changes:
- Pull in structopt (e2475e0)
- Add base struct for global options (007dfef)
- Add subcommand enum for selecting from multiple operations (007dfef)
- Remove static version variable in lieu of pulling in cargo defined env var at compile time (968b943)
  - Keeps up to date with releases automatically
- Add in default script name `./.comfy` to `main.rs` for case where none supplied (007dfef)
- Change `parser.rs` to take validated `PathBuf` (007dfef)

### CODE REVIEW

**Comment by oldwomanjosiah** [comment]
It would be worthwhile to note that this would be considered a breaking change in the release cycle as it (in its current state) changes the semantics of running the binary somewhat.

In the old version you always had to specify a file like so
```bash
comfy --file example.comfy
```
whereas now it will a) try to find the default if none is specified (this could be changed to an error instead relatively easily) and b) requires it be called like so to select a different script
```bash
comfy run examply.comfy
```

**Comment by Vagelis-Prokopiou** [comment]
I would strongly recommend using clap. It is pretty much the standard fro Rust.

**Comment by oldwomanjosiah** [comment]
> I would strongly recommend using clap. It is pretty much the standard for Rust.

structopt [uses clap ^2.33](https://crates.io/crates/structopt/0.3.21/dependencies) under the hood. What would be your main reasoning for using clap directly?

**Comment by Vagelis-Prokopiou** [comment]
> > I would strongly recommend using clap. It is pretty much the standard for Rust.
> 
> structopt [uses clap ^2.33](https://crates.io/crates/structopt/0.3.21/dependencies) under the hood. What would be your main reasoning for using clap directly?

That's interesting indeed. I had the impression that structopt was a different approach compared to clap. But it is an extension. And it seems like a very useful one.
So, no objections here :-)

**Comment by dacousb** [comment]
Ok, I'm reviewing the changes. Your code looks great, as soon as I'm done I'll accept the Pull Request.

**Comment by dacousb** [comment]
@oldwomanjosiah One question, is this intentional? If not, I will try to fix it
image

**Comment by oldwomanjosiah** [comment]
@dacousb that is definitely a bug, and it appears to be due to how `Path` considers filenames that start with a `.`  
In my head I think of them as files with no name and whatever extension, but according to path they are files with a name that starts with a period and no extension.

Screen Shot 2021-03-21 at 12 37 30

This would probably be fixed most easily by changing the default file name, but could also be done by switching to checking for a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) at the beginning of the file. This may affect the cross-platform nature of the program as on Unix-like systems that would allow the script to be run like `./name.comfy` but on windows would not. Either way, changing the validation method should probably be a separate PR.

**Comment by oldwomanjosiah** [comment]
The two commits I just pushed to the PR fix the bug for now by changing the default name to `./run.comfy`, but the specific name should probably be discussed. I just wanted to make sure that the fix would work in practice as well as in theory.

**Comment by dacousb** [comment]
@oldwomanjosiah amazing! Just one more thing before merging everything. Shall we also make the `--c` argument functional?

**Comment by oldwomanjosiah** [comment]
For sure, in 665992a the long option for comments is changed to `--c` (it would seem that with structopt you don't have the option of having multiple options for the name of the long options :( ) and the `extern crate ...` is removed.

**Comment by dacousb** [comment]
Merged your commit! I've opened (and closed) a new pull request by accident. No need to worry, your code is there safe and sound.

**Pull request merged**
